version: "3.8"

services:
  app:
    build: .
    container_name: portal_server
    restart: always
    ports:
      - "1489:1489"
    links:
      - "mongo:mongo"
    volumes:
      - ./config_docker.yaml:/app/config.yaml
      - ./cert/certificate.crt:/app/cert/certificate.crt
      - ./cert/private.key:/app/cert/private.key
      - ./log.txt:/app/log.txt
    depends_on:
      mongo:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "500M"
        max-file: "10"
  mongo:
    image: mongo
    container_name: portal_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 10s
  mongo-express:
    image: mongo-express:latest
    container_name: portal_mongo_express
    restart: always
    ports:
      - "7081:8081"
    links:
      - "mongo:mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
    depends_on:
      mongo:
        condition: service_healthy
